MANAGE_BUTTON = 'MNG_BTN'
MANAGE_SITE_BUTTON = 'MNG_SITE_BTN'
MANAGE_BOT_BUTTON = 'MNG_BOT_BTN'

RECIPES_BUTTON = 'RCPS_BTN'
RECIPE_ONE_BUTTON = 'RCP_ONE_BTN'
RECIPE_LIST_INGREDIENTS = 'RCP_LST_ING_BTN'

DEVICES_BUTTON = 'DVCS_BTN'
DEVICE_ONE_BUTTON = 'DVCS_ONE_BTN'
DEVICE_DATA_BUTTON = 'DVCS_DATA_BTN'
DEVICE_CHART_BUTTON = 'DVCS_CHART_BTN'

CATALOG_BUTTON = 'CTLG_BTN'

MAIN_MENU_BUTTON = 'MENU_BTN'
